import SubCourses from "@/components/SubCourses/page";

export const data = [
  //**************************ESPCIAL KISSIMEE
  {
    id: "elementary-kissimmee",
    title: "Elementary Kissimmee",
    description2:
      "Push your child to discover a world of possibilities! Through fun learning, you will fall in love with English.",
    etapa: "6-11 years old. ",
    img: "elementaryCourse.png",
    imgAlternative: "elementaryAlt.png",
    price: 800,
    compra: true,
    inscripcion: 200,
    detalles: ["48 academic hours", "3 months per level"],
    difBlanco2: true,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Gives their access to global educational resources",
        src: "/img/difElem.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difElem2.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "3",
        title: "Develops their ability to adapt to new environments",
        src: "/img/difElem3.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "high-school-kissimmee",
    title: "High School Kissimmee",
    description2:
      "Prepare your child for the future. We combine exciting challenges with real projects so that your child acquires practical knowledge and develops their creativity.",
    etapa: "12-16 years old. ",
    img: "highSchoolCourse.png",
    imgAlternative: "highSchoolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    difBlanco2: true,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Preparation for academic tests: TOEFL y EILTS",
        src: "/img/difHS.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "2",
        title: "Practical and stimulating methodology for your age",
        src: "/img/difHS2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "3",
        title: "Boost your scholarship and study opportunities abroad",
        src: "/img/difHS3.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
    ],

    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "adults-kissimmee",
    title: "Adults Kissimmee",
    description2:
      "Communicate in English as you have always wanted, through practical and effective tools so that you speak fluently.",
    etapa: "+17 years old. ",
    img: "adultsCourse.png",
    imgAlternative: "adultsAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in English",
        src: "/img/difAdult.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Methodology aligned to the Common European Framework",
        src: "/img/difAdult2.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    horarios2: {
      horario: [
        {
          titulo: "Level 1 (Basic)",
          dia: "SATURDAYS",
          horas: ["9:00 am - 12:25 pm"],
        },
        {
          titulo: "Intermediate",
          dia: "TUESDAY AND THURSDAY",
          horas: ["9:00 - 10:40 am", "6:50 - 8:30 am"],
        },
        {
          titulo: "Advanced",
          dia: "SATURDAYS",
          horas: ["9:00 am - 12:20 pm"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "we have these specialized courses for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["financiado-level", "recomendado-level"],
  },
  //*****************************CURSOS PRESENCIAL */
  {
    id: "kids",
    title: "Kids",
    description2:
      "Safe and different learning. Through games, songs and creative activities, your child learns English in a fun and effective way.",
    etapa: "3-5 years old. ",
    img: "kidsCourse.png",
    imgAlternative: "kidsCourseAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Fun methodology designed for their learning stage",
        src: "/img/difKids.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
      {
        id: "2",
        title:
          "Take advantage of the plasticity of their brain to learn the language",
        src: "/img/difKids2.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
      {
        id: "3",
        title: "Achieve more accurate pronunciation from an early age",
        src: "/img/difKids3.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
    ],
    horarios: {
      horario: [
        {
          dia: "MONDAY AND WEDNESDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "FRIDAY",
          horas: ["2:00 - 5:00 pm"],
        },
        {
          dia: "SATURDAYS",
          horas: ["9:00 - 12:00 pm", "2:00 - 5:00 pm"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "elementary",
    title: "Elementary",
    description2:
      "Push your child to discover a world of possibilities! Through fun learning, you will fall in love with English.",
    etapa: "6-11 years old. ",
    img: "elementaryCourse.png",
    imgAlternative: "elementaryAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Gives their access to global educational resources",
        src: "/img/difElem.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difElem2.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "3",
        title: "Develops their ability to adapt to new environments",
        src: "/img/difElem3.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
    ],
    horarios: {
      horario: [
        {
          dia: "MONDAY AND WEDNESDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "FRIDAY",
          horas: ["2:00 - 5:00 pm"],
        },
        {
          dia: "SATURDAYS",
          horas: ["9:00 - 12:00 pm", "2:00 - 5:00 pm"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "high-school",
    title: "High School",
    description2:
      "Prepare your child for the future. We combine exciting challenges with real projects so that your child acquires practical knowledge and develops their creativity.",
    etapa: "12-16 years old. ",
    img: "highSchoolCourse.png",
    imgAlternative: "highSchoolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Preparation for academic tests: TOEFL and EILTS",
        src: "/img/difHS.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "2",
        title: "Practical and stimulating methodology for their age",
        src: "/img/difHS2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "3",
        title: "Boost their scholarship and study opportunities abroad",
        src: "/img/difHS3.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
    ],
    horarios: {
      horario: [
        {
          dia: "MONDAY AND WEDNESDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: ["2:00 - 3:20 pm", "3:30 - 4:50 pm", "5:00 - 6:20 pm"],
        },
        {
          dia: "FRIDAY",
          horas: ["2:00 - 5:00 pm"],
        },
        {
          dia: "SATURDAYS",
          horas: ["9:00 - 12:00 pm", "2:00 - 5:00 pm"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "adults",
    title: "Adults",
    description2:
      "Communicate in English as you have always wanted, through practical and effective tools so that you speak fluently.",
    etapa: "+17 years old. ",
    img: "adultsCourse.png",
    imgAlternative: "adultsAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in English",
        src: "/img/difAdult.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Methodology aligned to the Common European Framework",
        src: "/img/difAdult2.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    horarios: {
      horario: [
        {
          dia: "WEDNESDAY AND FRIDAY",
          horas: [
            "7:00 - 8:20 am",
            "8:30 - 9:50 am",
            "10:00 - 11:20 am",
            "12:30 - 1:50 pm",
          ],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: [
            "7:00 - 8:20 am",
            "8:30 - 9:50 am",
            "10:00 - 11:20 am",
            "12:30 - 1:50 pm",
          ],
        },
        {
          dia: "MONDAY AND WEDNESDAY",
          horas: ["6:30 - 7:50 pm"],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: ["6:30 - 7:50 pm"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "we have these specialized courses for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado", "intensivo"],
    },
    promo: ["financiado-level", "recomendado-level"],
  },
  {
    id: "personalizado",
    title: "Personalizado",
    description2:
      " Learn English at your own pace with an exclusive teacher, who adapts to your needs and objectives. Create your own path to English proficiency!",

    img: "personalizado.png",
    imgAlternative: "personalizadoAlt.png",
    price: 40,
    compra: true,
    etapa: "All ages.",
    personalized: [
      {
        img: "/img/persoEdad.png",
        title: "KIDS",
        subtitle: "3-5 years old",
      },
      {
        img: "/img/persoEdad4.png",
        title: "ELEMENTARY",
        subtitle: "6-11 years old",
      },
      {
        img: "/img/persoEdad2.png",
        title: "HIGH SCHOOL",
        subtitle: "12-17 years old",
      },
      {
        img: "/img/persoEdad3.png",
        title: "ADULTS",
        subtitle: "+17 years old",
      },
    ],
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "hora",
    difCourses: [
      {
        id: "1",
        title: "Learn at your pace",
        src: "/img/difPersonalizado.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
      {
        id: "2",
        title: "Exclusive Teacher",
        src: "/img/difPersonalizado2.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
      {
        id: "3",
        title: "Adapted to your needs and objectives",
        src: "/img/difPersonalizado3.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
    ],
    difTarjeta: [
      "Learn at your pace",
      "Exclusive teacher",
      "Adapted to your needs and objectives",
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "intensivo",
    title: "Intensivo",
    description2:
      "An Intensive English Course adapted to your needs. 8 hours a week and only a month and a half per level, it's time to boost your language skills.",
    img: "intensivo.png",
    imgAlternative: "intensivoAlt.png",
    price: 800,
    compra: true,
    intensivo: true,
    difBlanco: true,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Time flexibility",
        src: "/img/difIntensivo.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
      {
        id: "2",
        title: "Interactive classes",
        src: "/img/difIntensivo2.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
      {
        id: "3",
        title: "Constant practice",
        src: "/img/difIntensivo3.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
    ],
    difTarjeta: [
      "8 hours a week",
      "Month and a half per level",
      "Constant practice",
    ],
    horarios: {
      horario: [
        {
          dia: "WEDNESDAY AND FRIDAY",
          horas: [
            "7:00 - 8:20 am",
            "8:30 - 9:50 am",
            "10:00 - 11:20 am",
            "12:30 - 1:50 pm",
          ],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: [
            "7:00 - 8:20 am",
            "8:30 - 9:50 am",
            "10:00 - 11:20 am",
            "12:30 - 1:50 pm",
          ],
        },
        {
          dia: "MONDAY AND WEDNESDAY",
          horas: ["6:30 - 7:50 pm"],
        },
        {
          dia: "TUESDAY AND THURSDAY",
          horas: ["6:30 - 7:50 pm"],
        },
      ],
    },
    time: [
      { num: "6", titulo: "WEEKS" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "8", titulo: "HOURS PER WEEK" },
    ],
  },
  {
    id: "corporativo",
    title: "Corporativo",
    description2:
      "A flexible program adaptable to the needs of your company. We offer tailored solutions so that your team can master English.",

    img: "corporativo.png",
    imgAlternative: "corporativoAlt.png",
    corporativo: true,
    difBlanco: true,
    lang: "english",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Exclusive for companies",
        src: "/img/difCorporativoOnline.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "2",
        title: "Plan adapted to your needs",
        src: "/img/difCorporativoOnline2.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "3",
        title: "Schedule according to your requirements",
        src: "/img/difCorporativoOnline3.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
    ],
  },
  {
    id: "conversacional",
    title: "Conversacional",
    description2:
      "Do you want to expand your vocabulary? Sign up for our Conversational Course where you can practice your English and leave all the nerves behind.",
    img: "conversacional.png",
    imgAlternative: "conversacionalAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Expand vocabulary",
      "Small groups",
      "Improvement in pronunciation",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["ingles-para-negocios", "reduccion-de-acento"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "ingles-para-negocios",
    title: "Inglés para Negocios",
    description2:
      "Do you need to improve your vocabulary to function successfully in an international professional environment? Our Business English Course is your best option.",

    img: "inglesparanegocios.png",
    imgAlternative: "inglesparanegociosAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Specific vocabulary",
      "Idiomatic expressions",
      "Grammar applied to your branch",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["conversacional", "reduccion-de-acento"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "reduccion-de-acento",
    title: "Reducción de Acento",
    description2:
      "Focus on improving your pronunciation and fluency in English. Start today and transform the way you speak this language.",
    img: "reducciondeacento.png",
    imgAlternative: "reducciondeacentoAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "English phonetics",
      "Intonation and rhythm",
      "Word reduction",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["conversacional", "ingles-para-negocios"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "ciudadania-americana",
    title: "Curso de Ciudadanía",
    description2:
      "Forget about feeling nervous about having to communicate in English on your American Citizenship exam. Practice with real examples and achieve your dream.",

    img: "cursoCiudadania.png",
    imgAlternative: "cursoCiudadaniaAlt.png",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "presencial",
    modalityPayment: "hora",
    difBlanco: true,
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in English",
        src: "/img/difAdult.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Methodology aligned to the Common European Framework",
        src: "/img/difAdult2.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },

  //***********************ONLINE COURSES
  {
    id: "elementary-online",
    title: "Elementary Online",
    description2:
      "Push your child to discover a world of possibilities! Through fun learning, you will fall in love with English.",
    etapa: "6-11 years old. ",
    modalidad: "online",
    modalityPayment: "lapso",
    img: "elementaryOnline.png",
    imgAlternative: "elementaryOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    difCourses: [
      {
        id: "1",
        title: "Gives you access to global educational resources",
        src: "/img/difElem.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difElem2.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "3",
        title: "Develops your ability to adapt to new environments",
        src: "/img/difElem3.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
    ],
    horarios: {
      titulo: "Available times",
      horario: [
        {
          dia: "MONDAY TO THURSDAY",
          horas: ["3:00 - 3:50 pm", "(Venezuela time zone)"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-online"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "high-school-online",
    title: "High School Online",
    description2:
      "Prepare your child for the future, with a course adapted to their age. A perfect combination of topics and challenges adapted to your interests.",
    etapa: "12-16 years old. ",
    modalidad: "online",
    modalityPayment: "lapso",
    img: "highSchoolOnline.png",
    imgAlternative: "highSchoolOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    difCourses: [
      {
        id: "1",
        title: "Gives you access to global educational resources",
        src: "/img/difHSO.png",
        width: 60,
        height: 60,
        alt: "difHSO",
      },
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difHSO2.png",
        width: 60,
        height: 60,
        alt: "difHSO",
      },
      {
        id: "3",
        title: "Develops your ability to adapt to new environments",
        src: "/img/difHSO3.png",
        width: 60,
        height: 60,
        alt: "difHSO",
      },
    ],
    horarios: {
      titulo: "Available times",
      horario: [
        {
          dia: "MONDAY TO THURSDAY",
          horas: ["3:00 - 3:50 pm", "(Venezuela time zone)"],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-online"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "adults-online",
    title: "Adults Online",
    description2:
      "Communicate in English as you have always wanted, through practical and effective tools so that you speak fluently.",
    etapa: "+17 years old. ",
    modalidad: "online",
    modalityPayment: "nivel",
    img: "adultsOnline.png",
    imgAlternative: "adultsOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "english",
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in English",
        src: "/img/difAdult.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Methodology aligned to the Common European Framework",
        src: "/img/difAdult2.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    horarios: {
      titulo: "Horarios disponibles",
      horario: [
        {
          dia: "MONDAY & WENESDAY",
          horas: ["8:00pm - 9:50pm", "(EST)"],
        },
        {
          dia: "TUESDAY & THURSDAY",
          horas: [
            "9:00 am - 10:50 am",
            "6:00 pm - 7:50 pm",
            "8:00 pm - 9:50 pm",
            "(EST)",
          ],
        },
      ],
    },
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-online", "intensivo-online"],
    },
    promo: ["financiado-level", "recomendado-level"],
  },
  {
    id: "personalizado-online",
    title: "Personalizado Online",
    description2:
      "Learn English at your own pace with an exclusive teacher, who adapts to your needs and objectives. Create your own path to English proficiency!",
    modalidad: "online",
    modalityPayment: "hora",
    img: "personalizadoOnline.png",
    imgAlternative: "personalizadoOnlineAlt.png",
    compra: true,
    price: 40,
    etapa: "All ages.",
    personalized: [
      {
        img: "/img/persoEdad4.png",
        title: "ELEMENTARY",
        subtitle: "6-11 years old",
      },
      {
        img: "/img/persoEdad2.png",
        title: "HIGH SCHOOL",
        subtitle: "12-17 years old",
      },
      {
        img: "/img/persoEdad3.png",
        title: "ADULTS",
        subtitle: "+17 years old",
      },
    ],
    lang: "english",
    difCourses: [
      {
        id: "1",
        title: "Learn at your pace",
        src: "/img/difPersonalizadoOnline.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
      {
        id: "2",
        title: "Exclusive Teacher",
        src: "/img/difPersonalizadoOnline2.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
      {
        id: "3",
        title: "Adapted to your needs and objectives",
        src: "/img/difPersonalizadoOnline3.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
    ],
    difTarjeta: [
      "Learn at your pace",
      "Exclusive teacher",
      "Adapted to your needs and objectives",
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "intensivo-online",
    title: "Intensivo Online",
    description2:
      "An Intensive English Course adapted to your needs. 8 hours a week and only a month and a half per level, it's time to boost your language skills.",
    modalidad: "online",
    modalityPayment: "nivel",
    img: "intensivoOnline.png",
    imgAlternative: "intensivoOnlineAlt.png",
    price: 800,
    compra: true,
    difBlanco2: true,
    lang: "english",
    difCourses: [
      {
        id: "1",
        title: "Time flexibility",
        src: "/img/difIntensivoOnline.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
      {
        id: "2",
        title: "Interactive classes",
        src: "/img/difIntensivoOnline2.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
      {
        id: "3",
        title: "Constant practice",
        src: "/img/difIntensivoOnline3.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
    ],
    difTarjeta: [
      "8 hours a week",
      "Month and a half per level",
      "Constant practice",
    ],
    time: [
      { num: "6", titulo: "LEVELS" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "6", titulo: "WEEKS PER LEVEL" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-online", "intensivo-online"],
    },
  },
  {
    id: "corporativo-online",
    title: "Corporativo Online",
    description2:
      "A flexible program adaptable to the needs of your company. We offer tailored solutions so that your team can master English.",

    img: "corporativoOnline.png",
    imgAlternative: "corporativoOnlineAlt.png",
    difBlanco: true,
    lang: "english",
    modalidad: "online",

    difCourses: [
      {
        id: "1",
        title: "Exclusive for companies",
        src: "/img/difCorporativoOnline.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "2",
        title: "Plan adapted to your needs",
        src: "/img/difCorporativoOnline2.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "3",
        title: "Schedule according to your requirements",
        src: "/img/difCorporativoOnline3.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
    ],
  },
  {
    id: "conversacional-online",
    title: "Conversacional Online",
    description2:
      "Do you want to expand your vocabulary? Sign up for our Conversational Course where you can practice your English and leave all the nerves behind.",
    img: "conversacionalOnline.png",
    imgAlternative: "conversacionalOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Expand vocabulary",
      "Small groups",
      "Improvement in pronunciation",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["ingles-para-negocios-online", "reduccion-de-acento-online"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "ingles-para-negocios-online",
    title: "Inglés para Negocios Online",
    description2:
      "Do you need to improve your vocabulary to function successfully in an international professional environment? Our Business English Course is your best option.",

    img: "inglesparanegociosOnline.png",
    imgAlternative: "inglesparanegociosOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "Specific vocabulary",
        src: "/img/difipnOnline.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
      {
        id: "2",
        title: "Idiomatic expressions",
        src: "/img/difipnOnline2.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
      {
        id: "3",
        title: "Grammar applied to your branch",
        src: "/img/difipnOnline3.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
    ],
    difTarjeta: [
      "Specific vocabulary",
      "Idiomatic expressions",
      "Grammar applied to your branch",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["conversacional-online", "reduccion-de-acento-online"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "reduccion-de-acento-online",
    title: "Reducción de Acento Online",
    description2:
      "Focus on improving your pronunciation and fluency in English. Start today and transform the way you speak this language.",
    img: "reducciondeacentoOnline.png",
    imgAlternative: "reducciondeacentoOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "english",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "English phonetics",
        src: "/img/difreduccionOnline.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
      {
        id: "2",
        title: "Intonation and rhythm",
        src: "/img/difreduccionOnline2.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
      {
        id: "3",
        title: "Word reduction",
        src: "/img/difreduccionOnline3.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
    ],
    difTarjeta: [
      "English phonetics",
      "Intonation and rhythm",
      "Word reduction",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your English",
      subCurso: ["conversacional-online", "ingles-para-negocios-online"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "ciudadania-americana-online",
    title: "Curso de Ciudadanía Online",
    description2:
      "Forget about feeling nervous about having to communicate in English on your American Citizenship exam. Practice with real examples and achieve your dream.",

    img: "cursoCiudadaniaOnline.png",
    imgAlternative: "cursoCiudadaniaOnlineAlt.png",
    price: 40,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    difBlanco: true,
    lang: "english",
    modalidad: "online",
    modalityPayment: "hora",
    difCourses: [
      {
        id: "1",
        title: "Interview practice",
        src: "/img/difCiudadaniaOnline.png",
        width: 60,
        height: 60,
        alt: "difCiudadaniaOnline",
      },
      {
        id: "2",
        title: "Ongoing support",
        src: "/img/difCiudadaniaOnline2.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Flexible classes",
        src: "/img/difCiudadaniaOnline3.png",
        width: 60,
        height: 60,
        alt: "difCiudadaniaOnline",
      },
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },
  //*******************CURSOS ESPAÑOL
  {
    id: "kids-espanol",
    title: "Kids Español",
    description2:
      "Spanish has never been so fun. Through fun classes, your child will learn to communicate in this new language.",
    etapa: "3-5 years old. ",
    img: "kidsEspanol.png",
    imgAlternative: "kidsEspanolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Fun methodology designed for your learning stage",
        src: "/img/difKids.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
      {
        id: "2",
        title:
          "Take advantage of the plasticity of your brain to learn the language",
        src: "/img/difKids2.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
      {
        id: "3",
        title: "Achieve more accurate pronunciation from an early age",
        src: "/img/difKids3.png",
        width: 60,
        height: 60,
        alt: "dif kids",
      },
    ],
    time: [
      { num: "3", titulo: "MÓDULOS" },
      { num: "48", titulo: "HORAS ACADÉMICAS POR MÓDULO" },
      { num: "12", titulo: "SEMANAS POR MÓDULO" },
    ],
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "elementary-espanol",
    title: "Elementary Español",
    description2:
      "With songs and games, learning will be an unforgettable experience! With our program your child acquires the basics of Spanish in a solid and fun way",
    etapa: "6-11 years old. ",
    img: "elementaryEspanol.png",
    imgAlternative: "elementaryEspanolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difElem2.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "1",
        title: "Build trust",
        src: "/img/difEspa.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "3",
        title: "Develops your ability to adapt to new environments",
        src: "/img/difElem3.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol"],
    },
    time: [
      { num: "3", titulo: "MÓDULOS" },
      { num: "48", titulo: "HORAS ACADÉMICAS POR MÓDULO" },
      { num: "12", titulo: "SEMANAS POR MÓDULO" },
    ],
    promo: ["essential-modulo", "recomendado-modulo"],
  },

  {
    id: "high-school-espanol",
    title: "High School Español",
    description2:
      "Through real conversations, cultural activities and lots of fun, your child develops all the skills necessary to communicate fluently and confidently.",
    etapa: "12-16 years old. ",
    img: "highSchoolEspanol.png",
    imgAlternative: "highSchoolEspanolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Focus on real communication and culture",
        src: "/img/difEspa2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "2",
        title: "Practical and stimulating methodology for their age",
        src: "/img/difHS2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "3",
        title: "Development of advanced linguistic skills",
        src: "/img/difEspa3.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol"],
    },
    time: [
      { num: "3", titulo: "MÓDULOS" },
      { num: "48", titulo: "HORAS ACADÉMICAS POR MÓDULO" },
      { num: "12", titulo: "SEMANAS POR MÓDULO" },
    ],
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "adults-espanol",
    title: "Adults Español",
    description2:
      "Learn Spanish in a natural and fun way, through practical and dynamic classes that will help you improve your fluency in the language.",
    etapa: "+17 years old. ",
    img: "adultsEspanol.png",
    imgAlternative: "adultsEspanolAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    difBlanco2: true,
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in Spanish",
        src: "/img/difEspa4.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Benefit in professional development",
        src: "/img/difEspa5.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "we have these specialized courses for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol", "intensivo-espanol"],
    },
    promo: ["financiado-level", "recomendado-level"],
  },
  {
    id: "intensivo-espanol",
    title: "Intensivo Español",
    description2:
      "An Intensive Spanish Course adapted to your objectives. 8 hours a week and only a month and a half per level, it's time to boost your language skills.",
    img: "intensivoEspanol.png",
    imgAlternative: "intensivoEspanolAlt.png",
    price: 800,
    compra: true,
    intensivo: true,
    difBlanco2: true,
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Time flexibility",
        src: "/img/difIntensivo.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
      {
        id: "2",
        title: "Interactive classes",
        src: "/img/difIntensivo2.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
      {
        id: "3",
        title: "Constant practice",
        src: "/img/difIntensivo3.png",
        width: 60,
        height: 60,
        alt: "dif intensivo",
      },
    ],
    difTarjeta: [
      "8 hours a week",
      "Month and a half per level",
      "Constant practice",
    ],

    time: [
      { num: "6", titulo: "WEEKS" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "8", titulo: "HOURS PER WEEK" },
    ],
    subCursos: {
      titulo: "we have these specialized courses for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol", "intensivo-espanol"],
    },
  },
  {
    id: "personalizado-espanol",
    title: "Personalizado Español",
    description2:
      "Do you need a more personal approach? Get to know our Personalized Spanish Course. Achieve your goals at your own pace and with an exclusive teacher.",
    etapa: "All ages.",
    img: "personalizadoEspanol.png",
    imgAlternative: "personalizadoEspanolAlt.png",
    price: 40,
    compra: true,
    personalized: [
      {
        img: "/img/persoEdad4.png",
        title: "ELEMENTARY",
        subtitle: "6-11 years old",
      },
      {
        img: "/img/persoEdad2.png",
        title: "HIGH SCHOOL",
        subtitle: "12-17 years old",
      },
      {
        img: "/img/persoEdad3.png",
        title: "ADULTS",
        subtitle: "+17 years old",
      },
    ],
    lang: "spanish",
    modalidad: "presencial",
    modalityPayment: "hora",

    difCourses: [
      {
        id: "1",
        title: "Learn at your pace",
        src: "/img/difPersonalizado.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
      {
        id: "2",
        title: "Exclusive Teacher",
        src: "/img/difPersonalizado2.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
      {
        id: "3",
        title: "Adapted to your needs and objectives",
        src: "/img/difPersonalizado3.png",
        width: 60,
        height: 60,
        alt: "difPersonalizado",
      },
    ],
    difTarjeta: [
      "Learn at your pace",
      "Exclusive teacher",
      "Adapted to your needs and objectives",
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "conversacional-espanol",
    title: "Conversacional Español",
    description2:
      "Do you want to expand your vocabulary? Sign up for our Conversational Course where you can practice your Spanish and leave all the nerves behind.",
    img: "conversacionalEspanol.png",
    imgAlternative: "conversacionalEspanolAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Expand vocabulary",
      "Small groups",
      "Improvement in pronunciation",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish.",
      subCurso: ["espanol-para-negocios", "reduccion-de-acento-espanol"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "espanol-para-negocios",
    title: "Español para Negocios",
    description2:
      "Do you need to improve your vocabulary to function successfully in an international professional environment? Our Business Spanish Course is your best option.",

    img: "espanolparanegocios.png",
    imgAlternative: "espanolparanegociosAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Specific vocabulary",
      "Idiomatic expressions",
      "Grammar applied to your branch",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish",
      subCurso: ["conversacional-espanol", "reduccion-de-acento-espanol"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "reduccion-de-acento-espanol",
    title: "Reducción de Acento Español",
    description2:
      "Focus on improving your pronunciation and fluency when speaking Spanish. Start today and transform the way you speak Spanish.",
    img: "reducciondeacentoEspanol.png",
    imgAlternative: "reducciondeacentoEspanolAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "English phonetics",
      "Intonation and rhythm",
      "Word reduction",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish",
      subCurso: ["conversacional-espanol", "espanol-para-negocios"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "corporativo-espanol",
    title: "Corporativo Español",
    description2:
      "A course focused on the needs of your company. We offer tailored solutions so that your team can master Spanish.",

    img: "corporativoEspanol.png",
    imgAlternative: "corporativoEspanolAlt.png",
    corporativo: true,
    difBlanco: true,
    lang: "spanish",
    modalidad: "presencial",
    difCourses: [
      {
        id: "1",
        title: "Exclusive for companies",
        src: "/img/difCorporativoOnline.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "2",
        title: "Plan adapted to your needs",
        src: "/img/difCorporativoOnline2.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "3",
        title: "Schedule according to your requirements",
        src: "/img/difCorporativoOnline3.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
    ],
  },
  //***********************ESPAÑOL ONLINE
  {
    id: "elementary-espanol-online",
    title: "Elementary Español Online",
    description2:
      "With songs and games, learning will be an unforgettable experience! With our program your child acquires the basics of Spanish in a solid and fun way.",
    etapa: "6-11 years old. ",
    img: "elementaryEspanolOnline.png",
    imgAlternative: "elementaryEspanolOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    difBlanco2: true,
    lang: "spanish",
    modalidad: "online",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "2",
        title: "Improves their academic performance at school",
        src: "/img/difElem2.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "1",
        title: "Build trust",
        src: "/img/difEspa.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
      {
        id: "3",
        title: "Develops your ability to adapt to new environments",
        src: "/img/difElem3.png",
        width: 60,
        height: 60,
        alt: "difElem",
      },
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol-online"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "high-school-espanol-online",
    title: "High School Español Online",
    description2:
      "Through real conversations, cultural activities and lots of fun, your child develops all the skills necessary to communicate fluently and confidently.",
    etapa: "12-16 years old. ",
    img: "highSchoolEspanolOnline.png",
    imgAlternative: "highSchoolEspanolOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    difBlanco2: true,
    lang: "spanish",
    modalidad: "online",
    modalityPayment: "lapso",
    difCourses: [
      {
        id: "1",
        title: "Focus on real communication and culture",
        src: "/img/difEspa2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "2",
        title: "Practical and stimulating methodology for their age",
        src: "/img/difHS2.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
      {
        id: "3",
        title: "Development of advanced linguistic skills",
        src: "/img/difEspa3.png",
        width: 60,
        height: 60,
        alt: "difHS",
      },
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS PER PERIOD" },
      { num: "4", titulo: "ACADEMIC HOURS PER PERIOD" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol-online"],
    },
    promo: ["essential-modulo", "recomendado-modulo"],
  },
  {
    id: "adults-espanol-online",
    title: "Adults Español Online",
    description2:
      "Learn Spanish in a natural and fun way, through practical and dynamic classes that will help you improve your fluency in the language.",
    etapa: "+17 years old. ",
    img: "adultsEspanolOnline.png",
    imgAlternative: "adultsEspanolOnlineAlt.png",
    price: 800,
    compra: true,
    detalles: ["48 academic hours", "3 months per level"],
    inscripcion: 200,
    difBlanco2: true,
    lang: "spanish",
    modalidad: "online",
    modalityPayment: "nivel",
    difCourses: [
      {
        id: "1",
        title: "Classes 100% in Spanish",
        src: "/img/difEspa4.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "2",
        title: "Benefit in professional development",
        src: "/img/difEspa5.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
      {
        id: "3",
        title: "Small groups",
        src: "/img/difAdult3.png",
        width: 60,
        height: 60,
        alt: "difAdult",
      },
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "we have these specialized courses for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol-online", "intensivo-espanol-online"],
    },
    promo: ["financiado-level", "recomendado-level"],
  },
  {
    id: "personalizado-espanol-online",
    title: "Personalizado Español Online",
    description2:
      "Do you need a more personal approach? Get to know our Personalized Spanish Course. Achieve your goals at your own pace and with an exclusive teacher.",
    etapa: "All ages.",
    modalidad: "online",
    modalityPayment: "hora",
    img: "personalizadoEspanolOnline.png",
    imgAlternative: "personalizadoEspanolOnlineAlt.png",
    price: 40,
    compra: true,
    personalized: [
      {
        img: "/img/persoEdad4.png",
        title: "ELEMENTARY",
        subtitle: "6-11 years old",
      },
      {
        img: "/img/persoEdad2.png",
        title: "HIGH SCHOOL",
        subtitle: "12-17 years old",
      },
      {
        img: "/img/persoEdad3.png",
        title: "ADULTS",
        subtitle: "+17 years old",
      },
    ],
    lang: "spanish",
    difCourses: [
      {
        id: "1",
        title: "Learn at your pace",
        src: "/img/difPersonalizadoOnline.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
      {
        id: "2",
        title: "Exclusive Teacher",
        src: "/img/difPersonalizadoOnline2.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
      {
        id: "3",
        title: "Adapted to your needs and objectives",
        src: "/img/difPersonalizadoOnline3.png",
        width: 60,
        height: 60,
        alt: "difPersonalizadoOnline",
      },
    ],
    difTarjeta: [
      "Learn at your pace",
      "Exclusive teacher",
      "Adapted to your needs and objectives",
    ],
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "intensivo-espanol-online",
    title: "Intensivo Español Online",
    description2:
      "An Intensive Spanish Course adapted to your objectives. 8 hours a week and only a month and a half per level, it's time to boost your language skills.",
    modalidad: "online",
    modalityPayment: "nivel",
    img: "intensivoEspanolOnline.png",
    imgAlternative: "intensivoEspanolOnlineAlt.png",
    price: 800,
    compra: true,
    difBlanco2: true,
    lang: "spanish",
    difCourses: [
      {
        id: "1",
        title: "Time flexibility",
        src: "/img/difIntensivoOnline.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
      {
        id: "2",
        title: "Interactive classes",
        src: "/img/difIntensivoOnline2.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
      {
        id: "3",
        title: "Constant practice",
        src: "/img/difIntensivoOnline3.png",
        width: 60,
        height: 60,
        alt: "difIntensivoOnline",
      },
    ],
    difTarjeta: [
      "8 hours a week",
      "Month and a half per level",
      "Constant practice",
    ],
    time: [
      { num: "12", titulo: "WEEKS PER LEVEL" },
      { num: "48", titulo: "ACADEMIC HOURS BY LEVEL" },
      { num: "4", titulo: "ACADEMIC HOURS BY WEEK" },
    ],
    subCursos: {
      titulo: "our Personalized Course is for you",
      subtitulo: "If you are looking for something more focused on your needs,",
      subCurso: ["personalizado-espanol-online"],
    },
  },
  {
    id: "corporativo-espanol-online",
    title: "Corporativo Español Online",
    description2:
      "A course focused on the needs of your company. We offer tailored solutions so that your team can master Spanish.",

    img: "corporativoEspanolOnline.png",
    imgAlternative: "corporativoEspanolOnlineAlt.png",
    difBlanco: true,
    lang: "spanish",
    modalidad: "online",

    difCourses: [
      {
        id: "1",
        title: "Exclusive for companies",
        src: "/img/difCorporativoOnline.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "2",
        title: "Plan adapted to your needs",
        src: "/img/difCorporativoOnline2.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
      {
        id: "3",
        title: "Schedule according to your requirements",
        src: "/img/difCorporativoOnline3.png",
        width: 60,
        height: 60,
        alt: "difCorporativoOnline",
      },
    ],
  },
  {
    id: "conversacional-espanol-online",
    title: "Conversacional Español Online",
    description2:
      "Do you want to expand your vocabulary? Sign up for our Conversational Course where you can practice your Spanish and leave all the nerves behind.",
    img: "conversacionalEspanolOnline.png",
    imgAlternative: "conversacionalEspanolOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "Expand vocabulary",
        src: "/img/difProfesional.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "2",
        title: "Small groups",
        src: "/img/difProfesional2.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
      {
        id: "3",
        title: "Improvement in pronunciation",
        src: "/img/difProfesional3.png",
        width: 60,
        height: 60,
        alt: "difProfesional",
      },
    ],
    difTarjeta: [
      "Expand vocabulary",
      "Small groups",
      "Improvement in pronunciation",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish",

      subCurso: [
        "espanol-para-negocios-online",
        "reduccion-de-acento-espanol-online",
      ],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },

  {
    id: "espanol-para-negocios-online",
    title: "Español para Negocios Online",
    description2:
      "Do you need to improve your vocabulary to function successfully in an international professional environment? Our Business Spanish Course is your best option.",

    img: "espanolparanegociosOnline.png",
    imgAlternative: "espanolparanegociosOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "Specific vocabulary",
        src: "/img/difipnOnline.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
      {
        id: "2",
        title: "Idiomatic expressions",
        src: "/img/difipnOnline2.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
      {
        id: "3",
        title: "Grammar applied to your branch",
        src: "/img/difipnOnline3.png",
        width: 60,
        height: 60,
        alt: "difipnOnline",
      },
    ],
    difTarjeta: [
      "Specific vocabulary",
      "Idiomatic expressions",
      "Grammar applied to your branch",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish",

      subCurso: [
        "conversacional-espanol-online",
        "reduccion-de-acento-espanol-online",
      ],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
  {
    id: "reduccion-de-acento-espanol-online",
    title: "Reducción de Acento Español Online",
    description2:
      "Focus on improving your pronunciation and fluency when speaking Spanish. Start today and transform the way you speak Spanish.",
    img: "reducciondeacentoEspanolOnline.png",
    imgAlternative: "reducciondeacentoEspanolOnlineAlt.png",
    condicion: "C1 onwards",
    etapa: "C1 onwards. ",
    modalityPayment: "hora",
    price: 40,
    compra: true,
    lang: "spanish",
    modalidad: "online",
    difCourses: [
      {
        id: "1",
        title: "English phonetics",
        src: "/img/difreduccionOnline.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
      {
        id: "2",
        title: "Intonation and rhythm",
        src: "/img/difreduccionOnline2.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
      {
        id: "3",
        title: "Word reduction",
        src: "/img/difreduccionOnline3.png",
        width: 60,
        height: 60,
        alt: "difreduccionOnline",
      },
    ],
    difTarjeta: [
      "English phonetics",
      "Intonation and rhythm",
      "Word reduction",
    ],
    subCursos: {
      titulo:
        "It's time to take that step in your professional career and improve your Spanish",
      subCurso: ["conversacional-online", "ingles-para-negocios-online"],
    },
    promo: ["essential-hora", "deluxe-hora"],
  },
];
