export const data = [
  /*PROMO POR NIVEL *****************************************/
  {
    id: "financiado-level",
    titulo: "FINANCED",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Level",
    descuento: 10,
    precioAnterior: 800,
    precioPromo: 240,
    financiado: {
      descripcion: "Inscription: 240$",
      descripcion2: " +  2 installments of: 240$",
      boton: "INSCRIPTION 240$",
    },
    detalles: [
      "3 Months",
      "1 Level",
      "Promo Financiado por nivel, inscripción: $240.00 + 2 cuotas: $240.00$",
    ],
    img: "financiadonivel.png",
  },
  {
    id: "recomendado-level",
    titulo: "RECOMENDED",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Levels",
    descuento: 30,
    precioAnterior: 800,
    precioPromo: 560,
    destacar: true,
    detalles: ["3 Months", "1 Level", "Promo DELUXE por nivel"],
    img: "recomendadonivel.png",
  },
  {
    id: "deluxe-level",
    titulo: "DELUXE",
    tiempoUnitario: "6 Months",
    tiempoTotal: "2 Levels",
    descuento: 40,
    precioAnterior: 1600,
    precioPromo: 960,
    detalles: ["6 Months", "2 Level", "Promo DELUXE por nivel"],
    img: "extranivel.png",
  },
  /*PROMO POR LAPSO ******************************************/
  {
    id: "essential-modulo",
    titulo: "FINANCED",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Module",
    descuento: 10,
    precioAnterior: 800,
    precioPromo: 240,
    financiado: {
      descripcion: "Inscription: 240$",
      descripcion2: " +  2 installments of: 240$",
      boton: "INSCRIPTION 240$",
    },
    detalles: [
      "3 Months",
      "1 Module",
      "Promo Financiado por módulo, inscripción: $240.00 + 2 cuotas: $240.00$",
    ],
    img: "financiadomodulo.png",
  },
  {
    id: "recomendado-lapso",
    titulo: "RECOMENDED",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Lapsos",
    descuento: 30,
    precioAnterior: 800,
    precioPromo: 560,
    detalles: ["3 Months", "1 Module", "Promo Recomendado por Module"],
    destacar: true,
    img: "recomendadomodulo.png",
  },
  {
    id: "deluxe-lapso",
    titulo: "DELUXE",
    tiempoUnitario: "6 Months",
    tiempoTotal: "2 Modules",
    descuento: 40,
    precioAnterior: 1600,
    precioPromo: 960,
    detalles: ["6 Months", "2 Modules", "Promo Deluxe por Módulo"],
    img: "deluxemodulo.png",
  },
  /*PROMO POR HORA ******************************************/
  {
    id: "essential-hora",
    titulo: "ESSENTIAL",
    tiempoUnitario: "16 Hours",
    tiempoTotal: "Exclusive teacher",
    descuento: 10,
    precioAnterior: 640,
    precioPromo: 576,
    detalles: ["16 horas", "Exclusive teacher", "Promo ESSENTIAL por hora"],
    img: "essentialhora.png",
  },
  {
    id: "recomendado-hora",
    titulo: "RECOMENDED",
    tiempoUnitario: "48 Hours",
    tiempoTotal: "Exclusive teacher",
    descuento: 30,
    precioAnterior: 1920,
    precioPromo: 1344,
    destacar: true,
    detalles: ["48 horas", "Exclusive teacher", "Promo RECOMENDED por hora"],
    img: "recomendadohora.png",
  },
  {
    id: "deluxe-hora",
    titulo: "DELUXE",
    tiempoUnitario: "24 Hours",
    tiempoTotal: "Exclusive teacher",
    descuento: 20,
    precioAnterior: 960,
    precioPromo: 768,
    detalles: ["24 horas", "Exclusive teacher", "Promo DELUXE por hora"],
    img: "deluxehora.png",
  },
]
