export const data = [
  {
    id: "essential-level",
    titulo: "ESSENTIAL",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Level",
    descuento: 30,
    precioAnterior: 800,
    precioPromo: 560,
  },
  {
    id: "extra-level",
    titulo: "EXTRA",
    tiempoUnitario: "6 Months",
    tiempoTotal: "2 Levels",
    descuento: 40,
    precioAnterior: 1600,
    precioPromo: 960,
  },
  {
    id: "deluxe-level",
    titulo: "DELUXE",
    tiempoUnitario: "9 Months",
    tiempoTotal: "3 Level",
    descuento: 50,
    precioAnterior: 2400,
    precioPromo: 1200,
    destacar: true,
  },
  {
    id: "essential-lapso",
    titulo: "ESSENTIAL",
    tiempoUnitario: "3 Months",
    tiempoTotal: "1 Lapse",
    descuento: 30,
    precioAnterior: 800,
    precioPromo: 560,
  },
  {
    id: "deluxe-lapso",
    titulo: "DELUXE",
    tiempoUnitario: "9 Months",
    tiempoTotal: "3 Lapses",
    descuento: 50,
    precioAnterior: 2400,
    precioPromo: 1200,
  },
  {
    id: "recomendado-lapso",
    titulo: "RECOMMENDED",
    tiempoUnitario: "6 Months",
    tiempoTotal: "2 Lapses",
    descuento: 40,
    precioAnterior: 1600,
    precioPromo: 960,
    destacar: true,
  },
  {
    id: "essential-hora",
    titulo: "ESSENTIAL",
    tiempoUnitario: "48 Horas",
    tiempoTotal: "1 Nivel",
    descuento: 30,
    precioAnterior: 1920,
    precioPromo: 1344,
  },
  {
    id: "deluxe-hora",
    titulo: "DELUXE",
    tiempoUnitario: "144 Horas",
    tiempoTotal: "3 Niveles",
    descuento: 50,
    precioAnterior: 5760,
    precioPromo: 2880,
    destacar: true,
  },
  {
    id: "extra-hora",
    titulo: "EXTRA",
    tiempoUnitario: "96 Horas",
    tiempoTotal: "2 Niveles",
    descuento: 40,
    precioAnterior: 3840,
    precioPromo: 2304,
  },
]
